name: Jekyll GH Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'

    - name: Install dependencies
      run: npm install

    - name: Build and deploy
      run: npm start

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        branch: gh-pages
        folder: _site
